In [1]:
import numpy as np
import os
from scipy.io import netcdf
import lpr
import time
import datetime
import scipy.io as sio

In [2]:
os.chdir('/nas2_nchc/j40bjt00/data/luhung/')
data_cwb = []
data_epa = []
for i in range(1998, 2017):
    data_cwb.append(np.genfromtxt('cwb_'+str(i)+'.txt'))
    data_epa.append(np.genfromtxt('epa_'+str(i)+'.txt'))


In [3]:
range_lat = np.array([25.3, 21])
range_lon = np.array([119, 123])

In [4]:
date = ['013100', '022800', '022900', '033100', '043000', '053100', '063000', '073100', '083100', '093000', '103100', '113000', '123100']
data_forecast = []
data_forecast_time = []
for i in range(1998, 2012):
    for j in date:
        if((j == '103100') | (j == '113000')):
            try:
                os.chdir('/nas2_nchc/j40bjt00/exp/ehtw/r85odM.T106O1Z60.10.606.ehtw.'+str(i)+j+'/hour/'+str(i)+'/')
                data = netcdf.netcdf_file('r85odM.T106O1Z60.10.606.ehtw_'+str(i)+'.temp2.nc', 'r')
                theyear_time = data.variables['time'].data
                lat = data.variables['lat'].data
                lat_range = np.array(np.where((lat <= range_lat[0]) & (lat >= range_lat[1]))).reshape(-1)
                lon = data.variables['lon'].data
                lon_range = np.array(np.where((lon <= range_lon[1]) & (lon >= range_lon[0]))).reshape(-1)
                theyear_data = data.variables['temp2'].data[:, lat_range, :][:, :, lon_range]
                os.chdir('/nas2_nchc/j40bjt00/exp/ehtw/r85odM.T106O1Z60.10.606.ehtw.'+str(i)+j+'/hour/'+str(i+1)+'/')
                data = netcdf.netcdf_file('r85odM.T106O1Z60.10.606.ehtw_'+str(i+1)+'.temp2.nc', 'r')
                nextyear_time = data.variables['time'].data
                lat = data.variables['lat'].data
                lat_range = np.array(np.where((lat <= range_lat[0]) & (lat >= range_lat[1]))).reshape(-1)
                lon = data.variables['lon'].data
                lon_range = np.array(np.where((lon <= range_lon[1]) & (lon >= range_lon[0]))).reshape(-1)
                nextyear_data = data.variables['temp2'].data[:, lat_range, :][:, :, lon_range]
                data_forecast_time.append(np.hstack((theyear_time, nextyear_time)))
                data_forecast.append(np.vstack((theyear_data, nextyear_data)))
            except:
                pass
        elif(j == '123100'):
            try:
                os.chdir('/nas2_nchc/j40bjt00/exp/ehtw/r85odM.T106O1Z60.10.606.ehtw.'+str(i)+j+'/hour/'+str(i+1)+'/')
                data = netcdf.netcdf_file('r85odM.T106O1Z60.10.606.ehtw_'+str(i+1)+'.temp2.nc', 'r')
                data_forecast_time.append(data.variables['time'].data)
                lat = data.variables['lat'].data
                lat_range = np.array(np.where((lat <= range_lat[0]) & (lat >= range_lat[1]))).reshape(-1)
                lon = data.variables['lon'].data
                lon_range = np.array(np.where((lon <= range_lon[1]) & (lon >= range_lon[0]))).reshape(-1)
                data_forecast.append(data.variables['temp2'].data[:, lat_range, :][:, :, lon_range])
            except:
                pass
        else:
            try:
                os.chdir('/nas2_nchc/j40bjt00/exp/ehtw/r85odM.T106O1Z60.10.606.ehtw.'+str(i)+j+'/hour/'+str(i)+'/')
                data = netcdf.netcdf_file('r85odM.T106O1Z60.10.606.ehtw_'+str(i)+'.temp2.nc', 'r')
                data_forecast_time.append(data.variables['time'].data)
                lat = data.variables['lat'].data
                lat_range = np.array(np.where((lat <= range_lat[0]) & (lat >= range_lat[1]))).reshape(-1)
                lon = data.variables['lon'].data
                lon_range = np.array(np.where((lon <= range_lon[1]) & (lon >= range_lon[0]))).reshape(-1)
                data_forecast.append(data.variables['temp2'].data[:, lat_range, :][:, :, lon_range])
            except:
                pass


/pkg/cfd/anaconda3/lib/python3.6/site-packages/scipy/io/netcdf.py:299: RuntimeWarning: Cannot close a netcdf_file opened with mmap=True, when netcdf_variables or arrays referring to its data still exist. All data arrays obtained from such files refer directly to data on disk, and must be copied before the file can be cleanly closed. (See netcdf_file docstring for more information on mmap.)
  ), category=RuntimeWarning)


In [5]:
month = ['01', '02', '03', '04', '05', '06', '07', '08', '09', '10', '11', '12']
day = ['0100', '0600', '1100', '1600', '2100', '2600']
for i in range(2012, 2017):
    for j in month:
        for k in day:
            if((j == '11') | (j == '12')):
                try:
                    os.chdir('/nas2_nchc/j40bjt00/exp/ehtw/r85odM.T106O1Z60.10.606.ehtw.'+str(i)+j+k+'/hour/'+str(i)+'/')
                    data = netcdf.netcdf_file('r85odM.T106O1Z60.10.606.ehtw_'+str(i)+'.temp2.nc', 'r')
                    theyear_time = data.variables['time'].data
                    lat = data.variables['lat'].data
                    lat_range = np.array(np.where((lat <= range_lat[0]) & (lat >= range_lat[1]))).reshape(-1)
                    lon = data.variables['lon'].data
                    lon_range = np.array(np.where((lon <= range_lon[1]) & (lon >= range_lon[0]))).reshape(-1)
                    theyear_data = data.variables['temp2'].data[:, lat_range, :][:, :, lon_range]
                    os.chdir('/nas2_nchc/j40bjt00/exp/ehtw/r85odM.T106O1Z60.10.606.ehtw.'+str(i)+j+k+'/hour/'+str(i+1)+'/')
                    data = netcdf.netcdf_file('r85odM.T106O1Z60.10.606.ehtw_'+str(i+1)+'.temp2.nc', 'r')
                    nextyear_time = data.variables['time'].data
                    lat = data.variables['lat'].data
                    lat_range = np.array(np.where((lat <= range_lat[0]) & (lat >= range_lat[1]))).reshape(-1)
                    lon = data.variables['lon'].data
                    lon_range = np.array(np.where((lon <= range_lon[1]) & (lon >= range_lon[0]))).reshape(-1)
                    nextyear_data = data.variables['temp2'].data[:, lat_range, :][:, :, lon_range]
                    data_forecast_time.append(np.hstack((theyear_time, nextyear_time)))
                    data_forecast.append(np.vstack((theyear_data, nextyear_data)))
                except:
                    pass
            else:
                try:
                    os.chdir('/nas2_nchc/j40bjt00/exp/ehtw/r85odM.T106O1Z60.10.606.ehtw.'+str(i)+j+k+'/hour/'+str(i)+'/')
                    data = netcdf.netcdf_file('r85odM.T106O1Z60.10.606.ehtw_'+str(i)+'.temp2.nc', 'r')
                    data_forecast_time.append(data.variables['time'].data)
                    lat = data.variables['lat'].data
                    lat_range = np.array(np.where((lat <= range_lat[0]) & (lat >= range_lat[1]))).reshape(-1)
                    lon = data.variables['lon'].data
                    lon_range = np.array(np.where((lon <= range_lon[1]) & (lon >= range_lon[0]))).reshape(-1)
                    data_forecast.append(data.variables['temp2'].data[:, lat_range, :][:, :, lon_range])
                except:
                    pass


/pkg/cfd/anaconda3/lib/python3.6/site-packages/scipy/io/netcdf.py:299: RuntimeWarning: Cannot close a netcdf_file opened with mmap=True, when netcdf_variables or arrays referring to its data still exist. All data arrays obtained from such files refer directly to data on disk, and must be copied before the file can be cleanly closed. (See netcdf_file docstring for more information on mmap.)
  ), category=RuntimeWarning)
Exception ignored in: <bound method netcdf_file.close of <scipy.io.netcdf.netcdf_file object at 0x7f2fcc6b7780>>
Traceback (most recent call last):
  File "/pkg/cfd/anaconda3/lib/python3.6/site-packages/scipy/io/netcdf.py", line 279, in close
    if not self.fp.closed:
AttributeError: 'netcdf_file' object has no attribute 'fp'


In [6]:
lat

array([ 89.14151943,  88.02942887,  86.91077081,  85.79062888,
        84.66992408,  83.54894691,  82.42781752,  81.30659452,
        80.18530987,  79.06398248,  77.94262425,  76.82124303,
        75.69984422,  74.57843166,  73.45700815,  72.33557575,
        71.21413608,  70.09269035,  68.97123954,  67.84978441,
        66.7283256 ,  65.60686361,  64.48539887,  63.36393171,
        62.24246244,  61.1209913 ,  59.9995185 ,  58.87804422,
        57.75656862,  56.63509184,  55.51361398,  54.39213516,
        53.27065546,  52.14917496,  51.02769373,  49.90621184,
        48.78472933,  47.66324626,  46.54176268,  45.42027863,
        44.29879413,  43.17730923,  42.05582395,  40.93433832,
        39.81285237,  38.69136612,  37.56987959,  36.4483928 ,
        35.32690576,  34.2054185 ,  33.08393102,  31.96244335,
        30.8409555 ,  29.71946747,  28.59797927,  27.47649093,
        26.35500245,  25.23351384,  24.1120251 ,  22.99053625,
        21.86904729,  20.74755823,  19.62606908,  18.50

In [7]:
lon

array([   0.   ,    1.125,    2.25 ,    3.375,    4.5  ,    5.625,
          6.75 ,    7.875,    9.   ,   10.125,   11.25 ,   12.375,
         13.5  ,   14.625,   15.75 ,   16.875,   18.   ,   19.125,
         20.25 ,   21.375,   22.5  ,   23.625,   24.75 ,   25.875,
         27.   ,   28.125,   29.25 ,   30.375,   31.5  ,   32.625,
         33.75 ,   34.875,   36.   ,   37.125,   38.25 ,   39.375,
         40.5  ,   41.625,   42.75 ,   43.875,   45.   ,   46.125,
         47.25 ,   48.375,   49.5  ,   50.625,   51.75 ,   52.875,
         54.   ,   55.125,   56.25 ,   57.375,   58.5  ,   59.625,
         60.75 ,   61.875,   63.   ,   64.125,   65.25 ,   66.375,
         67.5  ,   68.625,   69.75 ,   70.875,   72.   ,   73.125,
         74.25 ,   75.375,   76.5  ,   77.625,   78.75 ,   79.875,
         81.   ,   82.125,   83.25 ,   84.375,   85.5  ,   86.625,
         87.75 ,   88.875,   90.   ,   91.125,   92.25 ,   93.375,
         94.5  ,   95.625,   96.75 ,   97.875,   99.   ,  100.

In [8]:
len(data_forecast), len(data_forecast_time)

(511, 511)

In [9]:
os.chdir('/home/stu310309/data_forecast')
for i in range(len(data_forecast)):
    np.save('data_forecast'+str(i), data_forecast[i])
    np.save('data_forecast_time'+str(i), data_forecast_time[i])

In [10]:
n_lat_grid, n_lon_grid = 18, 11
n_day_grid, n_hour_grid = 45, 24
grid_shape = np.array([n_day_grid*n_hour_grid, n_lat_grid, n_lon_grid])
lat_grid, time_grid, lon_grid = np.meshgrid(np.linspace(25.4, 22, n_lat_grid).reshape(n_lat_grid, 1),
                                            np.arange(1, n_day_grid+1, 1/n_hour_grid).reshape(n_day_grid*n_hour_grid, 1),
                                            np.linspace(120, 122, n_lon_grid).reshape(n_lon_grid, 1))
t_grid = np.hstack((time_grid.reshape(n_lat_grid*n_day_grid*n_hour_grid*n_lon_grid, 1),
                    lat_grid.reshape(n_lat_grid*n_day_grid*n_hour_grid*n_lon_grid, 1),
                    lon_grid.reshape(n_lat_grid*n_day_grid*n_hour_grid*n_lon_grid, 1)))

In [11]:
temp_forecast = data_forecast[0][0:4*n_day_grid+1, :, :].reshape(1, -1)
time_index = np.array([data_forecast_time[0][0:4*n_day_grid+1].min(),
                       data_forecast_time[0][0:4*n_day_grid+1].max()]).reshape(1, 2)
for i in range(1, 153):
    temp_forecast = np.vstack((temp_forecast, data_forecast[i][0:4*n_day_grid+1, :, :].reshape(1, -1)))
    time_index = np.vstack((time_index,
                            np.array([data_forecast_time[i][0:4*n_day_grid+1].min(), 
                                      data_forecast_time[i][0:4*n_day_grid+1].max()]).reshape(1, 2)))
for i in np.arange(153, 502, 6):
    temp_forecast = np.vstack((temp_forecast, data_forecast[i][0:4*n_day_grid+1, :, :].reshape(1, -1)))
    time_index = np.vstack((time_index,
                            np.array([data_forecast_time[i][0:4*n_day_grid+1].min(), 
                                      data_forecast_time[i][0:4*n_day_grid+1].max()]).reshape(1, 2)))

In [12]:
temp_forecast.shape

(212, 2896)

In [13]:
time_forecast = np.linspace(1, n_day_grid+1, 4*n_day_grid+1)
lat_forecast = np.array([25.23351384, 24.1120251, 22.99053625, 21.86904729])
lon_forecast = np.array([119.25, 120.375, 121.5, 122.625])
s1_forecast, t1_forecast, s2_forecast = np.meshgrid(lat_forecast, time_forecast, lon_forecast)
t_forecast = np.hstack((t1_forecast.reshape(-1, 1),
                        s1_forecast.reshape(-1, 1),
                        s2_forecast.reshape(-1, 1))).reshape(-1, 3)

In [14]:
t_forecast.shape

(2896, 3)

In [15]:
time_index

array([[ 19980201.,  19980318.],
       [ 19980301.,  19980415.],
       [ 19980401.,  19980516.],
       [ 19980501.,  19980615.],
       [ 19980601.,  19980716.],
       [ 19980701.,  19980815.],
       [ 19980801.,  19980915.],
       [ 19980901.,  19981016.],
       [ 19981001.,  19981115.],
       [ 19981101.,  19981216.],
       [ 19981201.,  19990115.],
       [ 19990101.,  19990215.],
       [ 19990201.,  19990318.],
       [ 19990301.,  19990415.],
       [ 19990401.,  19990516.],
       [ 19990501.,  19990615.],
       [ 19990601.,  19990716.],
       [ 19990701.,  19990815.],
       [ 19990801.,  19990915.],
       [ 19990901.,  19991016.],
       [ 19991001.,  19991115.],
       [ 19991101.,  19991216.],
       [ 19991201.,  20000115.],
       [ 20010101.,  20010215.],
       [ 20010201.,  20010318.],
       [ 20010301.,  20010415.],
       [ 20010401.,  20010516.],
       [ 20010501.,  20010615.],
       [ 20010601.,  20010716.],
       [ 20010701.,  20010815.],
       [ 2

In [16]:
def last_time_interval(d):
    time_index_last_days = np.empty(time_index.shape)
    time_index_last_days[:, 1] = time_index[:, 0]
    time_delta = datetime.timedelta(d)
    for i in range(time_index_last_days.shape[0]):
        first_day = datetime.date(int(time_index[i, 0]/10000), 
                                  int((time_index[i, 0]-int(time_index[i, 0]/10000)*10000)/100),
                                  int(time_index[i, 0]-int(time_index[i, 0]/100)*100)) - time_delta
        time_index_last_days[i, 0] = first_day.year*10000 + first_day.month*100 + first_day.day
    return(time_index_last_days)

def Cut_obs_data(time_index):
    t_obs = []
    temp_obs = []
    for j in range(time_index.shape[0]):
        t_j = np.array([])
        temp_j = np.array([])
        for i in range(len(data_cwb)):
            data_cwb_time = data_cwb[i][:, 0]*10000 + data_cwb[i][:, 1]*100 + data_cwb[i][:, 2] + data_cwb[i][:, 3]/24
            data_epa_time = data_epa[i][:, 0]*10000 + data_epa[i][:, 1]*100 + data_epa[i][:, 2] + data_epa[i][:, 3]/24
            if any(((data_cwb_time>=time_index[j, 0])&(data_cwb_time<time_index[j, 1]))) | any((data_epa_time>=time_index[j, 0])&(data_epa_time<time_index[j, 1])):
                cwb_index = np.array(np.where((data_cwb_time>=time_index[j, 0])&(data_cwb_time<time_index[j, 1]))).reshape(-1)
                epa_index = np.array(np.where((data_epa_time>=time_index[j, 0])&(data_epa_time<time_index[j, 1]))).reshape(-1)
                time_obs = np.vstack((data_cwb_time[cwb_index].reshape(-1, 1), data_epa_time[epa_index].reshape(-1, 1)))
                time_min = datetime.date(int(time_index[j, 0]/10000), 
                                         int((time_index[j, 0]-int(time_index[j, 0]/10000)*10000)/100),
                                         int(time_index[j, 0]-int(time_index[j, 0]/100)*100))
                for k in range(time_obs.shape[0]):
                    time_obs[k] = (datetime.date(int(time_obs[k]/10000), 
                                                 int((time_obs[k]-int(time_obs[k]/10000)*10000)/100),
                                                 int(time_obs[k]-int(time_obs[k]/100)*100)) - time_min).days + time_obs[k]-int(time_obs[k]) + 1
                t_j = np.append(t_j, np.hstack((time_obs, np.vstack((data_cwb[i][cwb_index, :][:, np.array([6, 5])],
                                                                     data_epa[i][epa_index, :][:, np.array([6, 5])]))))).reshape(-1, 3)
                temp_j = np.append(temp_j, np.vstack((data_cwb[i][cwb_index, 7].reshape(-1, 1),
                                                      data_epa[i][epa_index, 7].reshape(-1, 1))).reshape(-1))
        t_obs.append(t_j)
        temp_obs.append(temp_j)
    return([t_obs, temp_obs])

In [17]:
time_index_last_7days = last_time_interval(7)
time_index_last_14days = last_time_interval(14)
time_index_last_21days = last_time_interval(21)

In [18]:
time_index_last_7days

array([[ 19980125.,  19980201.],
       [ 19980222.,  19980301.],
       [ 19980325.,  19980401.],
       [ 19980424.,  19980501.],
       [ 19980525.,  19980601.],
       [ 19980624.,  19980701.],
       [ 19980725.,  19980801.],
       [ 19980825.,  19980901.],
       [ 19980924.,  19981001.],
       [ 19981025.,  19981101.],
       [ 19981124.,  19981201.],
       [ 19981225.,  19990101.],
       [ 19990125.,  19990201.],
       [ 19990222.,  19990301.],
       [ 19990325.,  19990401.],
       [ 19990424.,  19990501.],
       [ 19990525.,  19990601.],
       [ 19990624.,  19990701.],
       [ 19990725.,  19990801.],
       [ 19990825.,  19990901.],
       [ 19990924.,  19991001.],
       [ 19991025.,  19991101.],
       [ 19991124.,  19991201.],
       [ 20001225.,  20010101.],
       [ 20010125.,  20010201.],
       [ 20010222.,  20010301.],
       [ 20010325.,  20010401.],
       [ 20010424.,  20010501.],
       [ 20010525.,  20010601.],
       [ 20010624.,  20010701.],
       [ 2

In [19]:
pre_time = time.time()
t_obs, temp_obs = Cut_obs_data(time_index)
t_obs_last_7days, temp_obs_last_7days = Cut_obs_data(time_index_last_7days)
t_obs_last_14days, temp_obs_last_14days = Cut_obs_data(time_index_last_14days)
t_obs_last_21days, temp_obs_last_21days = Cut_obs_data(time_index_last_21days)
time.time() - pre_time

1110.0879197120667

In [20]:
os.chdir('/home/stu310309/')
sio.savemat('data.mat',{'t_grid': t_grid, 'temp_forecast': temp_forecast, 't_forecast':t_forecast, 'temp_obs': temp_obs, 't_obs':t_obs, 'time_index':time_index})
sio.savemat('data_last_7days.mat',{'temp_obs_last_7days': temp_obs_last_7days, 't_obs_last_7days':t_obs_last_7days, 'time_index_last_7days':time_index_last_7days})
sio.savemat('data_last_14days.mat',{'temp_obs_last_14days': temp_obs_last_14days, 't_obs_last_14days':t_obs_last_14days, 'time_index_last_14days':time_index_last_14days})
sio.savemat('data_last_21days.mat',{'temp_obs_last_21days': temp_obs_last_21days, 't_obs_last_21days':t_obs_last_21days, 'time_index_last_21days':time_index_last_21days})